wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
epochs:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1741227561.772934
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.15.5
      8:
      - 2
      - 5
